<a href="https://colab.research.google.com/github/Thannos/Aula9/blob/master/Aula9_Paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [0]:
def troca( A): 
    for k in range(1,3):
      i=k+1
      n = np.shape(A)[0] - 1
      print('n ', n, '\ncolunas abaixo do pivo\n', np.array( A[ i : n + 1, k ] ) )
      colAbs = np.abs(A[ i : n + 1, k ])
      print( 'em módulo \n', colAbs )
      indexMax = np.argmax( colAbs )
      print( indexMax )
      iChange = indexMax + i
      print( iChange )
      aux = np.copy( A[ k, : ] )
      print('coluna a sofrer pivoteamento:', aux )
      A[ k, : ] = np.copy( A[ iChange, : ] )
      A[ iChange, : ] = np.copy( aux )
      #print(A,'\n')

In [0]:
def gaus(a,b,m,n):
  if np.linalg.det(a) == 0:
    print('Não é possível calcular matriz com determinante igual a 0')
    return
  aux=[]
  for i in range(0,(m-1)):
      for k in range(0, m): 
          if(a[k,k] == 0):
            troca(a)
          for r in range(k+1,m): 
            if(a[r,k] != 0):
              resp = (a[r,k]/a[k,k])
              aux.append(resp)
              b[r] -= (resp*b[k])
              for c in range(0,n):
                  a[r,c] -= (resp*a[k,c])
                  #print('a\n',a)
  print('Resultado matriz:\n',a,'\nResultado do vetor:\n',b,'\nResultados: ',aux)

In [0]:
def verifica(b, b1, m): #matriz-exp e matriz-p3
  aux=0
  for i in range(0,m):
    for j in range(0,m):
      for t in range(j,m):
        if((b[i,j]!=b[i,t])):
          while(b[i,j] < b[i,t]):
            b[i,j]+=1
            b1[i,j]/=10
            aux+=1
          while(b[i,j] > b[i,t]):
            b[i,t]+=1
            b1[i,t]/=10
            aux+=1
          print('precisão diferente\n',b[i,j],'!=',b[i,t])

In [0]:
def gaus2(a,a1,a2,b1,b2,b3,m): #m-normal,m-p3,m-exp,v-normal,v-p3,v-exp,tam
  if (np.linalg.det(a1) == 0):
    print('Não é possível calcular matriz com determinante igual a 0')
    return
  aux=[]
  for i in range(0,(m-1)):
      for k in range(0, m):
          for r in range(k+1,m): 
            if(a1[r,k] != 0):
              verifica(a2, a1, m)
              resp = (a1[r,k]/a1[k,k])
              aux.append(resp)
              b2[r] -= (resp*b2[k])
              for c in range(0,n):
                  a1[r,c] -= (resp*a1[k,c])
                  #print('a\n',a)
  print('Resultado matriz:\n',a1,'\nResultado do vetor:\n',b,'\nResultados: ',aux)

In [0]:
#truncamento e arredondamento
def justdoit(x,count,limite):
  if(count>=limite): 
    a=x-int(x) 
    x=int(x)
    if(a>=0.5):
      x+=1

    cont=0
    while(x>1):
      x/=10
      cont+=1 
    
    print(round(x,count)," * (10 ^",cont-count,")")
  else:
    cont=0
    while(x>=1):
      x=x/10
      cont+=1
    
    print(round(x,cont)," * (10 ^",cont-count,")")
  return (round(x,cont)),(cont-count)

In [117]:
a  = np.matrix([[3, 2, 1, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
b = np.array([5,6,7,15])
print(a)
troca(a)
print(a)
print('-------------------------------------------------')
m=3
n=3
a = np.array([[3.,2.,4.], [1.,1.,2.], [4.,3.,-2.]])
b = np.array([1.,2.,3.])
print('matriz:\n',a,'\nvetor:\n',b)
gaus(a, b, m, n)
print('-------------------------------------------------')
m=3
n=3
a = np.array([[1,3,1],[1,1,-1],[3,11,5]] )
b = np.array([9,1,35])
print('matriz:\n',a,'\nvetor:\n',b)
gaus(a,b,m,n)
print('-------------------------------------------------')

[[ 3  2  1 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3 
colunas abaixo do pivo
 [[-3]
 [ 2]]
em módulo 
 [[3]
 [2]]
0
2
coluna a sofrer pivoteamento: [[0 1 0 3]]
n  3 
colunas abaixo do pivo
 [[4]]
em módulo 
 [[4]]
0
3
coluna a sofrer pivoteamento: [[0 1 0 3]]
[[ 3  2  1 -1]
 [ 0 -3 -5  7]
 [ 0  2  4  0]
 [ 0  1  0  3]]
-------------------------------------------------
matriz:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]] 
vetor:
 [1. 2. 3.]
Resultado matriz:
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]] 
Resultado do vetor:
 [ 1.00000000e+00  1.66666667e+00 -7.21644966e-16] 
Resultados:  [0.3333333333333333, 1.3333333333333333, 1.0000000000000002, 1.6653345369377346e-16]
-------------------------------------------------
matriz:
 [[ 1  3  1]
 [ 1  1 -1]
 [ 3 11  5]] 
vetor:
 [ 9  1 35]
Não é possível calcular matriz com determinante igual a 0
-------------------------------------------------


In [99]:
limite=3
m=2
#primeira linha com precisão de três digitos
x=0.0002
c=2
v=5
count=0
exp=[]
resp=[]
exp.append(x)
exp.append(c)
resp.append(v)
while(count!=(limite-1)):
  x*=10
  c*=10
  v*=10
  count+=1
x,y=justdoit(x,count,limite)
aux1=[]
aux1.append(y)
c,y=justdoit(c,count,limite)
aux1.append(y)
resp1=[]
v,y=justdoit(v,count,limite)
resp1.append(y)
novo=[]
teste=[]
novo.append(x)
novo.append(c)
teste.append(v)
#print(aux1)
#segundo linha com precisão de três digitos
x=2
c=2
v=6
count=0
exp1=[]
exp1.append(x)
exp1.append(c)
resp.append(v)
while(count!=(limite-1)):
  x*=10
  c*=10
  v*=10
  count+=1
x,y=justdoit(x,count,limite)
aux2=[]
aux2.append(y)
c,y=justdoit(c,count,limite)
aux2.append(y)
v,y=justdoit(v,count,limite)
resp1.append(y)
novo1=[]
novo1.append(x)
novo1.append(c)
teste.append(v)
#print(aux2)
a = np.array([exp, exp1]) #matriz normal
a1 =  np.array([aux1, aux2]) #expoentes
a2 = np.array([novo,novo1]) #matriz com precisão 3
c = np.array(resp) #vetor resposta
c1 = np.array(teste) #vetor resposta com precisão 3
c2 = np.array(resp1) #expoente vetor resposta
print(a,'\n')
print(a1,'\n')
print(a2,'\n')
print(c,'\n')
print(c1,'\n')
print(c2,'\n')
gaus(a,c,m,n)
print('-------------------------------------------------')
gaus2(a,a2,a1,c,c1,c2,m) #m-normal,m-p3,m-exp,v-normal,v-p3,v-exp,tam

0.0  * (10 ^ -2 )
0.2  * (10 ^ 1 )
0.5  * (10 ^ 1 )
0.2  * (10 ^ 1 )
0.2  * (10 ^ 1 )
0.6  * (10 ^ 1 )
[[2.e-04 2.e+00]
 [2.e+00 2.e+00]] 

[[-2  1]
 [ 1  1]] 

[[0.  0.2]
 [0.2 0.2]] 

[5 6] 

[0.5 0.6] 

[1 1] 

Resultado matriz:
 [[2.e-04 2.e+00]
 [0.e+00 2.e+00]] 
Resultado do vetor:
 [     5 -49994] 
Resultados:  [10000.0]
-------------------------------------------------
precisão diferente
 1 != 1
Resultado matriz:
 [[0.  0.2]
 [nan 0.2]] 
Resultado do vetor:
 [ 9  1 35] 
Resultados:  [inf]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in double_scalars
  from ipykernel import kernelapp as app
