<a href="https://colab.research.google.com/github/Thannos/Aula9/blob/master/Aula9_Paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [0]:
def slice(A):
  #Aarr  = np.array([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])

  #A = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
  print(A)

  k = 1 
  i = 2
  n = np.shape(A)[0] - 1#último index
  print('n ', n, '\n')

  #slicing
  print( np.array( A[ i : n + 1, k ] ) )

  #Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )
  print( 'colAbs \n', colAbs )

  indexMax = np.argmax( colAbs )
  print( indexMax )


  #Trocando a coluna
  iChange = indexMax + i
  print( iChange )

  aux = np.copy( A[ k, : ] )
  print( aux )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )

  print(A)

In [0]:
def comp(mat,lin,col, resp):
  for i in range(0,col):
    if(mat[lin,i]>resp):
      print('a[',lin,',',i,'] = ',mat[lin,i],' > ',resp)
      return 1
    
  return 0

In [55]:
def gaus(a,b,m,n):
  for i in range(0,2):
      for k in range(0, m): 
          for r in range(k+1,m): 
              resp = (a[r,k]/a[k,k])
              b[r] -= (resp*b[k])
              for c in range(0,n):
                  a[r,c] -= (resp*a[k,c])
  print('Resultado matriz:\n',a,'\nResultado do vetor:\n',b,'\nResultados: ',resp)
m=3
n=3
a = np.array([[3.,2.,4.], [1.,1.,2.], [4.,3.,-2.]])
b = np.array([1.,2.,3.])
print('matriz:\n',a,'\nvetor:\n',b)
gaus(a, b, m, n)

matriz:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]] 
vetor:
 [1. 2. 3.]
Resultado matriz:
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]] 
Resultado do vetor:
 [ 1.00000000e+00  1.66666667e+00 -7.21644966e-16] 
Resultados:  1.6653345369377346e-16


In [12]:
np.linalg.det(a) #calcula determinante de uma matriz

-8.000000000000002

In [61]:
np.linalg.solve([[0.0002, 2], [2,2]], [5,6])

array([0.50005001, 2.49994999])