<a href="https://colab.research.google.com/github/Thannos/Aula9/blob/master/Aula9_Paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [0]:
def troca( A): 
    for k in range(1,3):
      i=k+1
      n = np.shape(A)[0] - 1
      print('n ', n, '\ncolunas abaixo do pivo\n', np.array( A[ i : n + 1, k ] ) )
      colAbs = np.abs(A[ i : n + 1, k ])
      print( 'em módulo \n', colAbs )
      indexMax = np.argmax( colAbs )
      print( indexMax )
      iChange = indexMax + i
      print( iChange )
      aux = np.copy( A[ k, : ] )
      print( aux )
      A[ k, : ] = np.copy( A[ iChange, : ] )
      A[ iChange, : ] = np.copy( aux )
      #print(A,'\n')

In [0]:
def gaus(a,b,m,n):
  for i in range(0,2):
      for k in range(0, m): 
          if(a[k,k] == 0):
            troca(a)
          for r in range(k+1,m): 
            if(a[r,k] != 0):
              resp = (a[r,k]/a[k,k])
              b[r] -= (resp*b[k])
              for c in range(0,n):
                  a[r,c] -= (resp*a[k,c])
  print('Resultado matriz:\n',a,'\nResultado do vetor:\n',b,'\nResultados: ',resp)

In [108]:
a  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
print(a)
troca(a)
print(a)
print('-------------------------------------------------')
m=3
n=3
a = np.array([[3.,2.,4.], [1.,1.,2.], [4.,3.,-2.]])
b = np.array([1.,2.,3.])
print('matriz:\n',a,'\nvetor:\n',b)
gaus(a, b, m, n)

[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3 
colunas abaixo do pivo
 [[-3]
 [ 2]]
em módulo 
 [[3]
 [2]]
0
2
[[0 1 0 3]]
n  3 
colunas abaixo do pivo
 [[4]]
em módulo 
 [[4]]
0
3
[[0 1 0 3]]
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  2  4  0]
 [ 0  1  0  3]]
-------------------------------------------------
matriz:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]] 
vetor:
 [1. 2. 3.]
Resultado matriz:
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]] 
Resultado do vetor:
 [ 1.00000000e+00  1.66666667e+00 -7.21644966e-16] 
Resultados:  1.6653345369377346e-16
