<a href="https://colab.research.google.com/github/Thannos/Aula9/blob/master/Aula9_Paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [0]:
def troca( A): 
    for k in range(1,3):
      i=k+1
      n = np.shape(A)[0] - 1
      print('n ', n, '\ncolunas abaixo do pivo\n', np.array( A[ i : n + 1, k ] ) )
      colAbs = np.abs(A[ i : n + 1, k ])
      print( 'em módulo \n', colAbs )
      indexMax = np.argmax( colAbs )
      print( indexMax )
      iChange = indexMax + i
      print( iChange )
      aux = np.copy( A[ k, : ] )
      print('coluna a sofrer pivoteamento:', aux )
      A[ k, : ] = np.copy( A[ iChange, : ] )
      A[ iChange, : ] = np.copy( aux )
      #print(A,'\n')

In [0]:
def gaus(a,b,m,n):
  if np.linalg.det(a) == 0:
    print('Não é possível calcular matriz com determinante igual a 0')
    return
  aux=[]
  for i in range(0,2):
      for k in range(0, m): 
          if(a[k,k] == 0):
            troca(a)
          for r in range(k+1,m): 
            if(a[r,k] != 0):
              resp = (a[r,k]/a[k,k])
              aux.append(resp)
              b[r] -= (resp*b[k])
              for c in range(0,n):
                  a[r,c] -= (resp*a[k,c])
                  #print('a\n',a)
  print('Resultado matriz:\n',a,'\nResultado do vetor:\n',b,'\nResultados: ',aux)

In [0]:
def gaus2(a,b,m,n):
  if np.linalg.det(a) == 0:
    print('Não é possível calcular matriz com determinante igual a 0')
    return
  aux=[]
  for i in range(0,2):
      for k in range(0, m): 
          if(a[k,k] == 0):
            troca(a)
          for r in range(k+1,m): 
            if(a[r,k] != 0):
              resp = (a[r,k]/a[k,k])
              aux.append(resp)
              b[r] -= (resp*b[k])
              for c in range(0,n):
                  a[r,c] -= (resp*a[k,c])
                  #print('a\n',a)
  print('Resultado matriz:\n',a,'\nResultado do vetor:\n',b,'\nResultados: ',aux)

In [0]:
#truncamento e arredondamento
def justdoit(x,count,limite):
  if(count>=limite): 
    a=x-int(x) 
    x=int(x)
    if(a>=0.5):
      x+=1

    cont=0
    while(x>1):
      x/=10
      cont+=1 
    
    print(round(x,count)," * (10 ^",cont-count,")")
  else:
    cont=0
    while(x>=1):
      x=x/10
      cont+=1
    
    print(round(x,cont)," * (10 ^",cont-count,")")
  return (round(x,cont)),(cont-count)

In [83]:
a  = np.matrix([[3, 2, 1, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
print(a)
troca(a)
print(a)
print('-------------------------------------------------')
m=3
n=3
a = np.array([[3.,2.,4.], [1.,1.,2.], [4.,3.,-2.]])
b = np.array([1.,2.,3.])
print('matriz:\n',a,'\nvetor:\n',b)
gaus(a, b, m, n)
print('-------------------------------------------------')
m=3
n=3
a = np.array([[1,3,1],[1,1,-1],[3,11,5]] )
b = np.array([9,1,35])
print('matriz:\n',a,'\nvetor:\n',b)
gaus(a,b,m,n)
print('-------------------------------------------------')

[[ 3  2  1 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3 
colunas abaixo do pivo
 [[-3]
 [ 2]]
em módulo 
 [[3]
 [2]]
0
2
coluna a sofrer pivoteamento: [[0 1 0 3]]
n  3 
colunas abaixo do pivo
 [[4]]
em módulo 
 [[4]]
0
3
coluna a sofrer pivoteamento: [[0 1 0 3]]
[[ 3  2  1 -1]
 [ 0 -3 -5  7]
 [ 0  2  4  0]
 [ 0  1  0  3]]
-------------------------------------------------
matriz:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]] 
vetor:
 [1. 2. 3.]
Resultado matriz:
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]] 
Resultado do vetor:
 [ 1.00000000e+00  1.66666667e+00 -7.21644966e-16] 
Resultados:  [0.3333333333333333, 1.3333333333333333, 1.0000000000000002, 1.6653345369377346e-16]
-------------------------------------------------
matriz:
 [[ 1  3  1]
 [ 1  1 -1]
 [ 3 11  5]] 
vetor:
 [ 9  1 35]
Não é possível calcular matriz com determinante igual a 0
-------------------------------------------------


In [89]:
a = np.array([[0.2, 0.2],[0.2,0.2]])
a1 = np.array([[-3,1],[1,1]])
b = np.array([0.5,0.6])
b1 = np.array([1,1])
n=2
print(a,'\n',b)
print('[[',end='')
for i in range(0,n):
  for j in range(0,n):
    print('(',a[i,j],'*(10^',a1[i,j],end='))   ')
  if(i<n-1):
    print(']\n')
  else:
    print(']]')

[[0.2 0.2]
 [0.2 0.2]] 
 [0.5 0.6]
[[( 0.2 *(10^ -3))   ( 0.2 *(10^ 1))   ]

( 0.2 *(10^ 1))   ( 0.2 *(10^ 1))   ]]


In [66]:
limite=3
#primeira linha com precisão de três digitos
x=3
c=2
v=4
count=0
while(count!=(limite-1)):
  x*=10
  c*=10
  v*=10
  count+=1
x,y1=justdoit(x,count,limite)
aux1=[]
aux1.append(x)
c,y2=justdoit(c,count,limite)
aux1.append(c)
v,y3=justdoit(v,count,limite)
aux1.append(v)
#print(aux1)
exp=[]
exp.append(y1)
exp.append(y2)
exp.append(y3)
#segundo linha com precisão de três digitos
x=1
c=1
v=2
count=0
while(count!=(limite-1)):
  x*=10
  c*=10
  v*=10
  count+=1
x,y1=justdoit(x,count,limite)
aux2=[]
aux2.append(x)
c,y2=justdoit(c,count,limite)
aux2.append(c)
v,y3=justdoit(v,count,limite)
aux2.append(v)
exp1=[]
exp1.append(y1)
exp1.append(y2)
exp1.append(y3)
#print(aux2)
#terceira linha com precisão de três digitos
x=4
c=3
v=2
count=0
while(count!=(limite-1)):
  x*=10
  c*=10
  v*=10
  count+=1
x,y1=justdoit(x,count,limite)
aux3=[]
aux3.append(x)
c,y2=justdoit(c,count,limite)
aux3.append(c)
v,y3=justdoit(v,count,limite)
aux3.append(v)
exp2=[]
exp2.append(y1)
exp2.append(y2)
exp2.append(y3)
#print(aux3)
a = np.array([aux1, aux2, aux3]) #matriz com precisão 3
a1 = np.array([exp, exp1, exp2]) #expoentes
print(a)

0.3  * (10 ^ 1 )
0.2  * (10 ^ 1 )
0.4  * (10 ^ 1 )
0.1  * (10 ^ 1 )
0.1  * (10 ^ 1 )
0.2  * (10 ^ 1 )
0.4  * (10 ^ 1 )
0.3  * (10 ^ 1 )
0.2  * (10 ^ 1 )
[[0.3 0.2 0.4]
 [0.1 0.1 0.2]
 [0.4 0.3 0.2]]
