In [0]:
import numpy as np

In [0]:
def gauss(a, b):
    n = len(a)
    x = np.zeros(n)
    for k in range(n - 1, -1, -1):
        s = 0
        for j in range(k + 1, n):
            s += a[k][j] * x[j]
        x[k] = (b[k] - s) / a[k][k]
    return x

In [0]:
def pivotamento(A, b):
    if (np.linalg.det(A) != 0):
        k=0
        n=1
        if (A[k][k] == 0):
          print('Erro na diagonal principal')
          return
        if (A[k + 1][k] != 0):
            for i in np.arange(k + 1, n + 1):
                m = A[i, k] / A[k, k]
                A[i, k] = 0
                for j in np.arange(k + 1, n + 1):
                    A[i, j] -= m * A[k, j]
                    b[i] -= m * b[k]

        return A, b
    else:
        print("Não é possível calcular matriz com determinante igual a 0")
        return

In [17]:
a=np.array([[0.0002, 2],[2, 2]])
b=np.array([5, 6])
print(a,'\n',b)
a, b = pivotamento(a, b)
print('\n',a,'\n',b)
print("solução: ", gauss(a,b).round(decimals=3))

[[2.e-04 2.e+00]
 [2.e+00 2.e+00]] 
 [5 6]

 [[ 2.0000e-04  2.0000e+00]
 [ 0.0000e+00 -1.9998e+04]] 
 [     5 -49994]
solução:  [0.5 2.5]


[[2.e-04 2.e+00]
 [2.e+00 2.e+00]] 
 [5 6]


NameError: ignored